[custom]
;原作者：https://github.com/Aethersailor
;项目地址：https://github.com/Aethersailor/Custom_OpenClash_Rules
;自用，适合移动设备长期挂载，规则更加精简

ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.list,28800
;own
ruleset=🎯 全球直连,https://raw.githubusercontent.com/atscfpoi/OMessyBanana/refs/heads/haha/ownrules.list,28800
ruleset=🛑 广告拦截,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.yaml,28800
ruleset=🇬 谷歌服务,https://raw.githubusercontent.com/atscfpoi/OMessyBanana/refs/heads/haha/ownrule/ownout.list,28800
ruleset=🎯 全球直连,https://raw.githubusercontent.com/atscfpoi/OMessyBanana/refs/heads/haha/ownrule/ownpass.list,28800
;分界线
ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.list,28800
ruleset=🎯 全球直连,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-cn.yaml,28800
ruleset=🎯 全球直连,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.yaml,28800
ruleset=🎯 全球直连,https://raw.githubusercontent.com/Aethersailor/Custom_OpenClash_Rules/main/rule/Steam_CDN.list,28800
ruleset=🎯 全球直连,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-game-platforms-download.yaml,28800
ruleset=🎯 全球直连,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.yaml,28800
ruleset=🎯 全球直连,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-cn.yaml,28800
ruleset=🎯 全球直连,[]GEOIP,CN,no-resolve
;分界线-尽可能仅保留国外网站
ruleset=🎓 学术论文,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-scholar-!cn.yaml,28800
ruleset=💬 即时通讯,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-communication.yaml,28800
ruleset=💬 即时通讯,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list,28800
ruleset=🌐 社交媒体,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-social-media-!cn.yaml,28800
ruleset=🌐 社交媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Twitter/Twitter.list,28800
ruleset=🌐 社交媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Facebook/Facebook.list,28800
ruleset=🤖 AI服务,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.yaml,28800
ruleset=🚀 GitHub,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml,28800
ruleset=🚀 GitHub,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/docker.yaml,28800
ruleset=🚀 测速工具,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-speedtest.yaml,28800
ruleset=📹 YouTube,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml,28800
ruleset=🍎 苹果服务,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.yaml,28800
ruleset=Ⓜ️ 微软服务,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.yaml,28800
ruleset=🇬 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.list,28800
ruleset=🇬 谷歌服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list,28800
ruleset=🎥 Netflix,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list,28800
ruleset=🎥 Emby,https://raw.githubusercontent.com/atscfpoi/OMessyBanana/refs/heads/haha/ownrule/ownemby.list,28800
ruleset=📺 Bahamut,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bahamut.yaml,28800
ruleset=🌎 国外媒体,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-entertainment.yaml,28800
ruleset=🌎 国外媒体,clash-classic:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GlobalMedia/GlobalMedia_No_Resolve.yaml,28800
ruleset=🛒 国外电商,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Amazon/Amazon.list,28800
ruleset=🛒 国外电商,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ecommerce.yaml,28800
ruleset=🎮 Steam,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.yaml,28800
ruleset=🎮 游戏平台,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.yaml,28800
ruleset=🚀 节点选择,clash-domain:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/DustinWin/ruleset_geodata/refs/heads/mihomo-ruleset/proxy.yaml,28800
ruleset=🚀 节点选择,clash-classic:https://gigabu.atscfpoi.top/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global_No_Resolve.yaml,28800
ruleset=🐟 漏网之鱼,[]FINAL
;设置节点分组标志位
custom_proxy_group=🚀 节点选择`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🌎 其他国家`^((?!.*(emby|Emby|EMBY|备|havefun)).)*$
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🚀 节点选择`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🛑 广告拦截`select`[]DIRECT`[]REJECT
custom_proxy_group=🎓 学术论文`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🎯 全球直连`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🌎 其他国家`[]🚀 节点选择
custom_proxy_group=🚀 GitHub`select`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点
custom_proxy_group=💬 即时通讯`select`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点
custom_proxy_group=🌐 社交媒体`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点
custom_proxy_group=🤖 AI服务`select`[]🇺🇸 美国节点`[]🇸🇬 新加坡节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🚀 节点选择
custom_proxy_group=📹 YouTube`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🎥 Netflix`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🎥 Emby`select`[]🎬️ Emby`[]🤗 SG优化`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇸🇬 新加坡节点
custom_proxy_group=📺 Bahamut`select`[]🇹🇼 台湾节点`[]🇭🇰 香港节点`[]🎯 全球直连
custom_proxy_group=🌎 国外媒体`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🛒 国外电商`select`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家`[]🚀 节点选择
custom_proxy_group=🇬 谷歌服务`select`[]🤗 SG优化`[]🇸🇬 新加坡节点`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇹🇼 台湾节点`[]🌎 其他国家`[]🎯 全球直连
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=Ⓜ️ 微软服务`select`[]🇭🇰 香港节点`[]🎯 全球直连`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🎮 游戏平台`select`[]🎯 全球直连`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🎮 Steam`select`[]🇭🇰 香港节点`[]🎯 全球直连`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🚀 测速工具`select`[]🚀 节点选择`[]🎯 全球直连`[]🤗 SG优化`[]🇭🇰 香港节点`[]🇺🇸 美国节点`[]🇯🇵 日本节点`[]🇸🇬 新加坡节点`[]🇹🇼 台湾节点`[]🌎 其他国家
custom_proxy_group=🎯 全球直连`select`[]DIRECT
;设置分组标志位
custom_proxy_group=🇭🇰 香港节点`url-test`(?=.*(港|HK|hk|Hong Kong|HongKong|hongkong|深港))^((?!.*(emby|Emby|EMBY|备|普)).)*$`https://www.google.com/generate_204`300,,25
custom_proxy_group=🇺🇸 美国节点`url-test`(?=.*(美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates))^((?!.*(emby|Emby|EMBY|备)).)*$`https://www.google.com/generate_204`300,,25
custom_proxy_group=🇯🇵 日本节点`url-test`(?=.*(日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|🇯🇵))^((?!.*(emby|Emby|EMBY|备)).)*$`https://www.google.com/generate_204`300,,25
custom_proxy_group=🇸🇬 新加坡节点`url-test`(?=.*(新加坡|坡|狮城|SG|Singapore))^((?!.*(emby|Emby|EMBY|备|普)).)*$`https://www.google.com/generate_204`300,,25
custom_proxy_group=🇹🇼 台湾节点`url-test`(?=.*(台|新北|彰化|TW|Taiwan))^((?!.*(emby|Emby|EMBY|备)).)*$`https://www.google.com/generate_204`300,,25
custom_proxy_group=🌎 其他国家`select`^(?!.*(emby|Emby|EMBY|备|港|HK|hk|Hong Kong|HongKong|hongkong|深港|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States|UnitedStates|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|(?<!尼|-)日|JP|Japan|🇯🇵|新加坡|坡|狮城|SG|Singapore|台|新北|彰化|TW|Taiwan)).*$
custom_proxy_group=🤗 SG优化`fallback`(havefun)`[]🇸🇬 新加坡节点`https://www.google.com/generate_204`120,,50
custom_proxy_group=🎬️ Emby`fallback`(havefun)`[]🇭🇰 香港节点`(emby|Emby|EMBY)`https://www.google.com/generate_204`120,,50
;下方参数请勿修改
enable_rule_generator=true
overwrite_original_rules=true
clash_rule_base=https://raw.githubusercontent.com/atscfpoi/OMessyBanana/refs/heads/haha/base/clash_base_now.yml
